# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    telegraf.yaml                                      :+:    :+:             #
#                                                      +:+                     #
#    By: akramp <akramp@student.codam.nl>             +#+                      #
#                                                    +#+                       #
#    Created: 2020/12/13 13:27:36 by akramp        #+#    #+#                  #
#    Updated: 2020/12/14 20:16:58 by akramp        ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccount: user
      containers:
      - name: telegraf
        image: telegraf
        imagePullPolicy: Never
        ports:
        - containerPort: 8125
